# Generated by Django 4.1.2 on 2022-10-27 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("album", "0002_alter_album_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="duration",
            field=models.IntegerField(
                blank=True,
                default=0,
                help_text="works in seconds",
                verbose_name="duration",
            ),
        ),
    ]
