# Generated by Django 4.1.2 on 2022-10-26 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=250, verbose_name="full name"),
                ),
                (
                    "sumary",
                    models.TextField(blank=True, null=True, verbose_name="sumary"),
                ),
            ],
            options={
                "verbose_name": "Artist",
                "verbose_name_plural": "Artists",
            },
        ),
    ]
